/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "cpu_rpc_prot.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
rpc_checkpoint_1(int *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, rpc_checkpoint, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
rpc_deinit_1(int *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, rpc_deinit, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
rpc_printmessage_1(char *arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_printmessage,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_dlopen_1(char *arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_dlopen,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_register_function_1(ptr arg1, ptr arg2, char *arg3, char *arg4, int arg5, int arg6, ptr_result *clnt_res,  CLIENT *clnt)
{
	rpc_register_function_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	arg.arg4 = arg4;
	arg.arg5 = arg5;
	arg.arg6 = arg6;
	return (clnt_call (clnt, rpc_register_function, (xdrproc_t) xdr_rpc_register_function_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_ptr_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_elf_load_1(mem_data arg1, ptr arg2, int *clnt_res,  CLIENT *clnt)
{
	rpc_elf_load_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	return (clnt_call (clnt, rpc_elf_load, (xdrproc_t) xdr_rpc_elf_load_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_elf_unload_1(ptr arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_elf_unload,
		(xdrproc_t) xdr_ptr, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_register_var_1(ptr arg1, ptr arg2, ptr arg3, char *arg4, int arg5, size_t arg6, int arg7, int arg8, int arg9, int *clnt_res,  CLIENT *clnt)
{
	rpc_register_var_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	arg.arg4 = arg4;
	arg.arg5 = arg5;
	arg.arg6 = arg6;
	arg.arg7 = arg7;
	arg.arg8 = arg8;
	arg.arg9 = arg9;
	return (clnt_call (clnt, rpc_register_var, (xdrproc_t) xdr_rpc_register_var_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_choose_device_1(mem_data arg1, int_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, CUDA_CHOOSE_DEVICE,
		(xdrproc_t) xdr_mem_data, (caddr_t) &arg1,
		(xdrproc_t) xdr_int_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_device_get_attribute_1(int arg1, int arg2, int_result *clnt_res,  CLIENT *clnt)
{
	cuda_device_get_attribute_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	return (clnt_call (clnt, CUDA_DEVICE_GET_ATTRIBUTE, (xdrproc_t) xdr_cuda_device_get_attribute_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_device_get_by_pci_bus_id_1(char *arg1, int_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, CUDA_DEVICE_GET_BY_PCI_BUS_ID,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &arg1,
		(xdrproc_t) xdr_int_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_device_get_cache_config_1(int_result *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, CUDA_DEVICE_GET_CACHE_CONFIG, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int_result, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
cuda_device_get_limit_1(int arg1, u64_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, CUDA_DEVICE_GET_LIMIT,
		(xdrproc_t) xdr_int, (caddr_t) &arg1,
		(xdrproc_t) xdr_u64_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_device_get_p2p_attribute_1(int arg1, int arg2, int arg3, int_result *clnt_res,  CLIENT *clnt)
{
	cuda_device_get_p2p_attribute_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	return (clnt_call (clnt, CUDA_DEVICE_GET_P2P_ATTRIBUTE, (xdrproc_t) xdr_cuda_device_get_p2p_attribute_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_device_get_pci_bus_id_1(int arg1, int arg2, str_result *clnt_res,  CLIENT *clnt)
{
	cuda_device_get_pci_bus_id_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	return (clnt_call (clnt, CUDA_DEVICE_GET_PCI_BUS_ID, (xdrproc_t) xdr_cuda_device_get_pci_bus_id_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_str_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_device_get_shared_mem_config_1(int_result *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, CUDA_DEVICE_GET_SHARED_MEM_CONFIG, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int_result, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
cuda_device_get_stream_priority_range_1(dint_result *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, CUDA_DEVICE_GET_STREAM_PRIORITY_RANGE, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_dint_result, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
cuda_device_get_texture_lmw_1(cuda_channel_format_desc arg1, int arg2, u64_result *clnt_res,  CLIENT *clnt)
{
	cuda_device_get_texture_lmw_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	return (clnt_call (clnt, CUDA_DEVICE_GET_TEXTURE_LMW, (xdrproc_t) xdr_cuda_device_get_texture_lmw_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_u64_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_device_reset_1(int *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, CUDA_DEVICE_RESET, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
cuda_device_set_cache_config_1(int arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, CUDA_DEVICE_SET_CACHE_CONFIG,
		(xdrproc_t) xdr_int, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_device_set_limit_1(int arg1, size_t arg2, int *clnt_res,  CLIENT *clnt)
{
	cuda_device_set_limit_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	return (clnt_call (clnt, CUDA_DEVICE_SET_LIMIT, (xdrproc_t) xdr_cuda_device_set_limit_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_device_set_shared_mem_config_1(int arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, CUDA_DEVICE_SET_SHARED_MEM_CONFIG,
		(xdrproc_t) xdr_int, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_device_synchronize_1(int *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, CUDA_DEVICE_SYNCHRONIZE, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
cuda_get_device_1(int_result *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, CUDA_GET_DEVICE, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int_result, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
cuda_get_device_count_1(int_result *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, CUDA_GET_DEVICE_COUNT, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int_result, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
cuda_get_device_flags_1(int_result *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, CUDA_GET_DEVICE_FLAGS, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int_result, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
cuda_get_device_properties_1(int arg1, cuda_device_prop_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, CUDA_GET_DEVICE_PROPERTIES,
		(xdrproc_t) xdr_int, (caddr_t) &arg1,
		(xdrproc_t) xdr_cuda_device_prop_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_set_device_1(int arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, CUDA_SET_DEVICE,
		(xdrproc_t) xdr_int, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_set_device_flags_1(int arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, CUDA_SET_DEVICE_FLAGS,
		(xdrproc_t) xdr_int, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_set_valid_devices_1(mem_data arg1, int arg2, int *clnt_res,  CLIENT *clnt)
{
	cuda_set_valid_devices_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	return (clnt_call (clnt, CUDA_SET_VALID_DEVICES, (xdrproc_t) xdr_cuda_set_valid_devices_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_get_error_name_1(int arg1, str_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, CUDA_GET_ERROR_NAME,
		(xdrproc_t) xdr_int, (caddr_t) &arg1,
		(xdrproc_t) xdr_str_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_get_error_string_1(int arg1, str_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, CUDA_GET_ERROR_STRING,
		(xdrproc_t) xdr_int, (caddr_t) &arg1,
		(xdrproc_t) xdr_str_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_get_last_error_1(int *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, CUDA_GET_LAST_ERROR, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
cuda_peek_at_last_error_1(int *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, CUDA_PEEK_AT_LAST_ERROR, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
cuda_ctx_reset_persisting_l2cache_1(int *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, CUDA_CTX_RESET_PERSISTING_L2CACHE, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
cuda_stream_copy_attributes_1(ptr arg1, ptr arg2, int *clnt_res,  CLIENT *clnt)
{
	cuda_stream_copy_attributes_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	return (clnt_call (clnt, CUDA_STREAM_COPY_ATTRIBUTES, (xdrproc_t) xdr_cuda_stream_copy_attributes_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_stream_create_1(ptr_result *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, CUDA_STREAM_CREATE, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_ptr_result, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
cuda_stream_create_with_flags_1(int arg1, ptr_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, CUDA_STREAM_CREATE_WITH_FLAGS,
		(xdrproc_t) xdr_int, (caddr_t) &arg1,
		(xdrproc_t) xdr_ptr_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_stream_create_with_priority_1(int arg1, int arg2, ptr_result *clnt_res,  CLIENT *clnt)
{
	cuda_stream_create_with_priority_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	return (clnt_call (clnt, CUDA_STREAM_CREATE_WITH_PRIORITY, (xdrproc_t) xdr_cuda_stream_create_with_priority_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_ptr_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_stream_destroy_1(ptr arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, CUDA_STREAM_DESTROY,
		(xdrproc_t) xdr_ptr, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_stream_get_flags_1(ptr arg1, int_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, CUDA_STREAM_GET_FLAGS,
		(xdrproc_t) xdr_ptr, (caddr_t) &arg1,
		(xdrproc_t) xdr_int_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_stream_get_priority_1(ptr arg1, int_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, CUDA_STREAM_GET_PRIORITY,
		(xdrproc_t) xdr_ptr, (caddr_t) &arg1,
		(xdrproc_t) xdr_int_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_stream_is_capturing_1(ptr arg1, int_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, CUDA_STREAM_IS_CAPTURING,
		(xdrproc_t) xdr_ptr, (caddr_t) &arg1,
		(xdrproc_t) xdr_int_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_stream_query_1(ptr arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, CUDA_STREAM_QUERY,
		(xdrproc_t) xdr_ptr, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_stream_synchronize_1(ptr arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, CUDA_STREAM_SYNCHRONIZE,
		(xdrproc_t) xdr_ptr, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_stream_wait_event_1(ptr arg1, ptr arg2, int arg3, int *clnt_res,  CLIENT *clnt)
{
	cuda_stream_wait_event_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	return (clnt_call (clnt, CUDA_STREAM_WAIT_EVENT, (xdrproc_t) xdr_cuda_stream_wait_event_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_thread_exchange_stream_capture_mode_1(int arg1, int_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, CUDA_THREAD_EXCHANGE_STREAM_CAPTURE_MODE,
		(xdrproc_t) xdr_int, (caddr_t) &arg1,
		(xdrproc_t) xdr_int_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_event_create_1(ptr_result *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, CUDA_EVENT_CREATE, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_ptr_result, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
cuda_event_create_with_flags_1(int arg1, ptr_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, CUDA_EVENT_CREATE_WITH_FLAGS,
		(xdrproc_t) xdr_int, (caddr_t) &arg1,
		(xdrproc_t) xdr_ptr_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_event_destroy_1(ptr arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, CUDA_EVENT_DESTROY,
		(xdrproc_t) xdr_ptr, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_event_elapsed_time_1(ptr arg1, ptr arg2, float_result *clnt_res,  CLIENT *clnt)
{
	cuda_event_elapsed_time_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	return (clnt_call (clnt, CUDA_EVENT_ELAPSED_TIME, (xdrproc_t) xdr_cuda_event_elapsed_time_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_float_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_event_query_1(ptr arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, CUDA_EVENT_QUERY,
		(xdrproc_t) xdr_ptr, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_event_record_1(ptr arg1, ptr arg2, int *clnt_res,  CLIENT *clnt)
{
	cuda_event_record_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	return (clnt_call (clnt, CUDA_EVENT_RECORD, (xdrproc_t) xdr_cuda_event_record_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_event_record_with_flags_1(ptr arg1, ptr arg2, int arg3, int *clnt_res,  CLIENT *clnt)
{
	cuda_event_record_with_flags_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	return (clnt_call (clnt, CUDA_EVENT_RECORD_WITH_FLAGS, (xdrproc_t) xdr_cuda_event_record_with_flags_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_event_synchronize_1(ptr arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, CUDA_EVENT_SYNCHRONIZE,
		(xdrproc_t) xdr_ptr, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_func_get_attributes_1(ptr arg1, mem_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, CUDA_FUNC_GET_ATTRIBUTES,
		(xdrproc_t) xdr_ptr, (caddr_t) &arg1,
		(xdrproc_t) xdr_mem_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_func_set_attributes_1(ptr arg1, int arg2, int arg3, int *clnt_res,  CLIENT *clnt)
{
	cuda_func_set_attributes_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	return (clnt_call (clnt, CUDA_FUNC_SET_ATTRIBUTES, (xdrproc_t) xdr_cuda_func_set_attributes_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_func_set_cache_config_1(ptr arg1, int arg2, int *clnt_res,  CLIENT *clnt)
{
	cuda_func_set_cache_config_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	return (clnt_call (clnt, CUDA_FUNC_SET_CACHE_CONFIG, (xdrproc_t) xdr_cuda_func_set_cache_config_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_func_set_shared_mem_config_1(ptr arg1, int arg2, int *clnt_res,  CLIENT *clnt)
{
	cuda_func_set_shared_mem_config_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	return (clnt_call (clnt, CUDA_FUNC_SET_SHARED_MEM_CONFIG, (xdrproc_t) xdr_cuda_func_set_shared_mem_config_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_launch_cooperative_kernel_1(ptr arg1, rpc_dim3 arg2, rpc_dim3 arg3, mem_data arg4, size_t arg5, ptr arg6, int *clnt_res,  CLIENT *clnt)
{
	cuda_launch_cooperative_kernel_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	arg.arg4 = arg4;
	arg.arg5 = arg5;
	arg.arg6 = arg6;
	return (clnt_call (clnt, CUDA_LAUNCH_COOPERATIVE_KERNEL, (xdrproc_t) xdr_cuda_launch_cooperative_kernel_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_launch_kernel_1(ptr arg1, rpc_dim3 arg2, rpc_dim3 arg3, mem_data arg4, size_t arg5, ptr arg6, int *clnt_res,  CLIENT *clnt)
{
	cuda_launch_kernel_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	arg.arg4 = arg4;
	arg.arg5 = arg5;
	arg.arg6 = arg6;
	return (clnt_call (clnt, CUDA_LAUNCH_KERNEL, (xdrproc_t) xdr_cuda_launch_kernel_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_occupancy_available_dsmpb_1(ptr arg1, int arg2, int arg3, u64_result *clnt_res,  CLIENT *clnt)
{
	cuda_occupancy_available_dsmpb_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	return (clnt_call (clnt, CUDA_OCCUPANCY_AVAILABLE_DSMPB, (xdrproc_t) xdr_cuda_occupancy_available_dsmpb_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_u64_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_occupancy_max_active_bpm_1(ptr arg1, int arg2, size_t arg3, int_result *clnt_res,  CLIENT *clnt)
{
	cuda_occupancy_max_active_bpm_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	return (clnt_call (clnt, CUDA_OCCUPANCY_MAX_ACTIVE_BPM, (xdrproc_t) xdr_cuda_occupancy_max_active_bpm_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_occupancy_max_active_bpm_with_flags_1(ptr arg1, int arg2, size_t arg3, int arg4, int_result *clnt_res,  CLIENT *clnt)
{
	cuda_occupancy_max_active_bpm_with_flags_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	arg.arg4 = arg4;
	return (clnt_call (clnt, CUDA_OCCUPANCY_MAX_ACTIVE_BPM_WITH_FLAGS, (xdrproc_t) xdr_cuda_occupancy_max_active_bpm_with_flags_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_array_get_info_1(ptr arg1, mem_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, CUDA_ARRAY_GET_INFO,
		(xdrproc_t) xdr_ptr, (caddr_t) &arg1,
		(xdrproc_t) xdr_mem_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_array_get_sparse_properties_1(ptr arg1, mem_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, CUDA_ARRAY_GET_SPARSE_PROPERTIES,
		(xdrproc_t) xdr_ptr, (caddr_t) &arg1,
		(xdrproc_t) xdr_mem_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_free_1(ptr arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, CUDA_FREE,
		(xdrproc_t) xdr_ptr, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_free_array_1(ptr arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, CUDA_FREE_ARRAY,
		(xdrproc_t) xdr_ptr, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_free_host_1(int arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, CUDA_FREE_HOST,
		(xdrproc_t) xdr_int, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_get_symbol_address_1(ptr arg1, ptr_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, CUDA_GET_SYMBOL_ADDRESS,
		(xdrproc_t) xdr_ptr, (caddr_t) &arg1,
		(xdrproc_t) xdr_ptr_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_get_symbol_size_1(ptr arg1, u64_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, CUDA_GET_SYMBOL_SIZE,
		(xdrproc_t) xdr_ptr, (caddr_t) &arg1,
		(xdrproc_t) xdr_u64_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_host_alloc_1(size_t arg1, u_int arg2, sz_result *clnt_res,  CLIENT *clnt)
{
	cuda_host_alloc_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	return (clnt_call (clnt, CUDA_HOST_ALLOC, (xdrproc_t) xdr_cuda_host_alloc_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_sz_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_host_alloc_regshm_1(size_t arg1, ptr arg2, int *clnt_res,  CLIENT *clnt)
{
	cuda_host_alloc_regshm_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	return (clnt_call (clnt, CUDA_HOST_ALLOC_REGSHM, (xdrproc_t) xdr_cuda_host_alloc_regshm_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_host_get_device_pointer_1(ptr arg1, int arg2, ptr_result *clnt_res,  CLIENT *clnt)
{
	cuda_host_get_device_pointer_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	return (clnt_call (clnt, CUDA_HOST_GET_DEVICE_POINTER, (xdrproc_t) xdr_cuda_host_get_device_pointer_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_ptr_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_host_get_flags_1(ptr arg1, int_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, CUDA_HOST_GET_FLAGS,
		(xdrproc_t) xdr_ptr, (caddr_t) &arg1,
		(xdrproc_t) xdr_int_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_malloc_1(size_t arg1, ptr_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, CUDA_MALLOC,
		(xdrproc_t) xdr_size_t, (caddr_t) &arg1,
		(xdrproc_t) xdr_ptr_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_malloc_3d_1(size_t arg1, size_t arg2, size_t arg3, pptr_result *clnt_res,  CLIENT *clnt)
{
	cuda_malloc_3d_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	return (clnt_call (clnt, CUDA_MALLOC_3D, (xdrproc_t) xdr_cuda_malloc_3d_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_pptr_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_malloc_3d_array_1(cuda_channel_format_desc arg1, size_t arg2, size_t arg3, size_t arg4, int arg5, ptr_result *clnt_res,  CLIENT *clnt)
{
	cuda_malloc_3d_array_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	arg.arg4 = arg4;
	arg.arg5 = arg5;
	return (clnt_call (clnt, CUDA_MALLOC_3D_ARRAY, (xdrproc_t) xdr_cuda_malloc_3d_array_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_ptr_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_malloc_array_1(cuda_channel_format_desc arg1, size_t arg2, size_t arg3, int arg4, ptr_result *clnt_res,  CLIENT *clnt)
{
	cuda_malloc_array_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	arg.arg4 = arg4;
	return (clnt_call (clnt, CUDA_MALLOC_ARRAY, (xdrproc_t) xdr_cuda_malloc_array_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_ptr_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_malloc_pitch_1(size_t arg1, size_t arg2, ptrsz_result *clnt_res,  CLIENT *clnt)
{
	cuda_malloc_pitch_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	return (clnt_call (clnt, CUDA_MALLOC_PITCH, (xdrproc_t) xdr_cuda_malloc_pitch_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_ptrsz_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_mem_advise_1(ptr arg1, size_t arg2, int arg3, int arg4, int *clnt_res,  CLIENT *clnt)
{
	cuda_mem_advise_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	arg.arg4 = arg4;
	return (clnt_call (clnt, CUDA_MEM_ADVISE, (xdrproc_t) xdr_cuda_mem_advise_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_mem_get_info_1(dsz_result *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, CUDA_MEM_GET_INFO, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_dsz_result, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
cuda_mem_prefetch_async_1(ptr arg1, size_t arg2, int arg3, ptr arg4, int *clnt_res,  CLIENT *clnt)
{
	cuda_mem_prefetch_async_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	arg.arg4 = arg4;
	return (clnt_call (clnt, CUDA_MEM_PREFETCH_ASYNC, (xdrproc_t) xdr_cuda_mem_prefetch_async_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_memcpy_htod_1(ptr arg1, mem_data arg2, size_t arg3, int *clnt_res,  CLIENT *clnt)
{
	cuda_memcpy_htod_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	return (clnt_call (clnt, CUDA_MEMCPY_HTOD, (xdrproc_t) xdr_cuda_memcpy_htod_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_memcpy_dtoh_1(ptr arg1, size_t arg2, mem_result *clnt_res,  CLIENT *clnt)
{
	cuda_memcpy_dtoh_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	return (clnt_call (clnt, CUDA_MEMCPY_DTOH, (xdrproc_t) xdr_cuda_memcpy_dtoh_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_mem_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_memcpy_shm_1(int arg1, ptr arg2, size_t arg3, int arg4, int *clnt_res,  CLIENT *clnt)
{
	cuda_memcpy_shm_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	arg.arg4 = arg4;
	return (clnt_call (clnt, CUDA_MEMCPY_SHM, (xdrproc_t) xdr_cuda_memcpy_shm_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_memcpy_dtod_1(ptr arg1, ptr arg2, size_t arg3, int *clnt_res,  CLIENT *clnt)
{
	cuda_memcpy_dtod_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	return (clnt_call (clnt, CUDA_MEMCPY_DTOD, (xdrproc_t) xdr_cuda_memcpy_dtod_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_memcpy_to_symbol_1(ptr arg1, mem_data arg2, size_t arg3, size_t arg4, int *clnt_res,  CLIENT *clnt)
{
	cuda_memcpy_to_symbol_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	arg.arg4 = arg4;
	return (clnt_call (clnt, CUDA_MEMCPY_TO_SYMBOL, (xdrproc_t) xdr_cuda_memcpy_to_symbol_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_memcpy_to_symbol_shm_1(int arg1, ptr arg2, size_t arg3, size_t arg4, int arg5, int *clnt_res,  CLIENT *clnt)
{
	cuda_memcpy_to_symbol_shm_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	arg.arg4 = arg4;
	arg.arg5 = arg5;
	return (clnt_call (clnt, CUDA_MEMCPY_TO_SYMBOL_SHM, (xdrproc_t) xdr_cuda_memcpy_to_symbol_shm_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_memcpy_ib_1(int arg1, ptr arg2, size_t arg3, int arg4, int *clnt_res,  CLIENT *clnt)
{
	cuda_memcpy_ib_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	arg.arg4 = arg4;
	return (clnt_call (clnt, CUDA_MEMCPY_IB, (xdrproc_t) xdr_cuda_memcpy_ib_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_memcpy_mt_htod_1(ptr arg1, size_t arg2, int arg3, dint_result *clnt_res,  CLIENT *clnt)
{
	cuda_memcpy_mt_htod_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	return (clnt_call (clnt, CUDA_MEMCPY_MT_HTOD, (xdrproc_t) xdr_cuda_memcpy_mt_htod_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_dint_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_memcpy_mt_dtoh_1(ptr arg1, size_t arg2, int arg3, dint_result *clnt_res,  CLIENT *clnt)
{
	cuda_memcpy_mt_dtoh_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	return (clnt_call (clnt, CUDA_MEMCPY_MT_DTOH, (xdrproc_t) xdr_cuda_memcpy_mt_dtoh_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_dint_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_memcpy_mt_sync_1(int arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, CUDA_MEMCPY_MT_SYNC,
		(xdrproc_t) xdr_int, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_memset_1(ptr arg1, int arg2, size_t arg3, int *clnt_res,  CLIENT *clnt)
{
	cuda_memset_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	return (clnt_call (clnt, CUDA_MEMSET, (xdrproc_t) xdr_cuda_memset_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_memset_2d_1(ptr arg1, size_t arg2, int arg3, size_t arg4, size_t arg5, int *clnt_res,  CLIENT *clnt)
{
	cuda_memset_2d_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	arg.arg4 = arg4;
	arg.arg5 = arg5;
	return (clnt_call (clnt, CUDA_MEMSET_2D, (xdrproc_t) xdr_cuda_memset_2d_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_memset_2d_async_1(ptr arg1, size_t arg2, int arg3, size_t arg4, size_t arg5, ptr arg6, int *clnt_res,  CLIENT *clnt)
{
	cuda_memset_2d_async_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	arg.arg4 = arg4;
	arg.arg5 = arg5;
	arg.arg6 = arg6;
	return (clnt_call (clnt, CUDA_MEMSET_2D_ASYNC, (xdrproc_t) xdr_cuda_memset_2d_async_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_memset_3d_1(size_t arg1, ptr arg2, size_t arg3, size_t arg4, int arg5, size_t arg6, size_t arg7, size_t arg8, int *clnt_res,  CLIENT *clnt)
{
	cuda_memset_3d_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	arg.arg4 = arg4;
	arg.arg5 = arg5;
	arg.arg6 = arg6;
	arg.arg7 = arg7;
	arg.arg8 = arg8;
	return (clnt_call (clnt, CUDA_MEMSET_3D, (xdrproc_t) xdr_cuda_memset_3d_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_memset_3d_async_1(size_t arg1, ptr arg2, size_t arg3, size_t arg4, int arg5, size_t arg6, size_t arg7, size_t arg8, ptr arg9, int *clnt_res,  CLIENT *clnt)
{
	cuda_memset_3d_async_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	arg.arg4 = arg4;
	arg.arg5 = arg5;
	arg.arg6 = arg6;
	arg.arg7 = arg7;
	arg.arg8 = arg8;
	arg.arg9 = arg9;
	return (clnt_call (clnt, CUDA_MEMSET_3D_ASYNC, (xdrproc_t) xdr_cuda_memset_3d_async_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_memset_async_1(ptr arg1, int arg2, size_t arg3, ptr arg4, int *clnt_res,  CLIENT *clnt)
{
	cuda_memset_async_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	arg.arg4 = arg4;
	return (clnt_call (clnt, CUDA_MEMSET_ASYNC, (xdrproc_t) xdr_cuda_memset_async_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_device_can_access_peer_1(int arg1, int arg2, int_result *clnt_res,  CLIENT *clnt)
{
	cuda_device_can_access_peer_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	return (clnt_call (clnt, CUDA_DEVICE_CAN_ACCESS_PEER, (xdrproc_t) xdr_cuda_device_can_access_peer_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_device_disable_peer_access_1(int arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, CUDA_DEVICE_DISABLE_PEER_ACCESS,
		(xdrproc_t) xdr_int, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_device_enable_peer_access_1(int arg1, int arg2, int *clnt_res,  CLIENT *clnt)
{
	cuda_device_enable_peer_access_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	return (clnt_call (clnt, CUDA_DEVICE_ENABLE_PEER_ACCESS, (xdrproc_t) xdr_cuda_device_enable_peer_access_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cuda_driver_get_version_1(int_result *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, CUDA_DRIVER_GET_VERSION, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int_result, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
cuda_runtime_get_version_1(int_result *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, CUDA_RUNTIME_GET_VERSION, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int_result, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
cuda_profiler_start_1(int *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, CUDA_PROFILER_START, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
cuda_profiler_stop_1(int *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, CUDA_PROFILER_STOP, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
rpc_cudevicegetcount_1(int_result *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, rpc_cuDeviceGetCount, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int_result, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
rpc_cuinit_1(int arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cuInit,
		(xdrproc_t) xdr_int, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudrivergetversion_1(int_result *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, rpc_cuDriverGetVersion, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int_result, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
rpc_cudeviceget_1(int arg1, int_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cuDeviceGet,
		(xdrproc_t) xdr_int, (caddr_t) &arg1,
		(xdrproc_t) xdr_int_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudevicegetname_1(int arg1, str_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cuDeviceGetName,
		(xdrproc_t) xdr_int, (caddr_t) &arg1,
		(xdrproc_t) xdr_str_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudevicetotalmem_1(int arg1, u64_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cuDeviceTotalMem,
		(xdrproc_t) xdr_int, (caddr_t) &arg1,
		(xdrproc_t) xdr_u64_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudevicegetattribute_1(int arg1, int arg2, int_result *clnt_res,  CLIENT *clnt)
{
	rpc_cudevicegetattribute_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	return (clnt_call (clnt, rpc_cuDeviceGetAttribute, (xdrproc_t) xdr_rpc_cudevicegetattribute_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudevicegetuuid_1(int arg1, str_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cuDeviceGetUuid,
		(xdrproc_t) xdr_int, (caddr_t) &arg1,
		(xdrproc_t) xdr_str_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cuctxgetcurrent_1(ptr_result *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, rpc_cuCtxGetCurrent, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_ptr_result, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
rpc_cuctxsetcurrent_1(ptr arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cuCtxSetCurrent,
		(xdrproc_t) xdr_ptr, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudeviceprimaryctxretain_1(int arg1, ptr_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cuDevicePrimaryCtxRetain,
		(xdrproc_t) xdr_int, (caddr_t) &arg1,
		(xdrproc_t) xdr_ptr_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cumodulegetfunction_1(ptr arg1, char *arg2, ptr_result *clnt_res,  CLIENT *clnt)
{
	rpc_cumodulegetfunction_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	return (clnt_call (clnt, rpc_cuModuleGetFunction, (xdrproc_t) xdr_rpc_cumodulegetfunction_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_ptr_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cumemalloc_1(ptr arg1, ptr_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cuMemAlloc,
		(xdrproc_t) xdr_ptr, (caddr_t) &arg1,
		(xdrproc_t) xdr_ptr_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cuctxgetdevice_1(int_result *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, rpc_cuCtxGetDevice, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int_result, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
rpc_cumemcpyhtod_1(ptr arg1, mem_data arg2, int *clnt_res,  CLIENT *clnt)
{
	rpc_cumemcpyhtod_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	return (clnt_call (clnt, rpc_cuMemcpyHtoD, (xdrproc_t) xdr_rpc_cumemcpyhtod_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_culaunchkernel_1(ptr arg1, u_int arg2, u_int arg3, u_int arg4, u_int arg5, u_int arg6, u_int arg7, u_int arg8, ptr arg9, mem_data arg10, int *clnt_res,  CLIENT *clnt)
{
	rpc_culaunchkernel_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	arg.arg4 = arg4;
	arg.arg5 = arg5;
	arg.arg6 = arg6;
	arg.arg7 = arg7;
	arg.arg8 = arg8;
	arg.arg9 = arg9;
	arg.arg10 = arg10;
	return (clnt_call (clnt, rpc_cuLaunchKernel, (xdrproc_t) xdr_rpc_culaunchkernel_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cumoduleload_1(char *arg1, ptr_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cuModuleLoad,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &arg1,
		(xdrproc_t) xdr_ptr_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cugeterrorstring_1(int arg1, str_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cuGetErrorString,
		(xdrproc_t) xdr_int, (caddr_t) &arg1,
		(xdrproc_t) xdr_str_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cumoduleunload_1(ptr arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cuModuleUnload,
		(xdrproc_t) xdr_ptr, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudeviceprimaryctxgetstate_1(int arg1, dint_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cuDevicePrimaryCtxGetState,
		(xdrproc_t) xdr_int, (caddr_t) &arg1,
		(xdrproc_t) xdr_dint_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudevicegetproperties_1(int arg1, mem_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cuDeviceGetProperties,
		(xdrproc_t) xdr_int, (caddr_t) &arg1,
		(xdrproc_t) xdr_mem_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudevicecomputecapability_1(int arg1, dint_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cuDeviceComputeCapability,
		(xdrproc_t) xdr_int, (caddr_t) &arg1,
		(xdrproc_t) xdr_dint_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudevicegetp2pattribute_1(int arg1, ptr arg2, ptr arg3, int_result *clnt_res,  CLIENT *clnt)
{
	rpc_cudevicegetp2pattribute_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	return (clnt_call (clnt, rpc_cuDeviceGetP2PAttribute, (xdrproc_t) xdr_rpc_cudevicegetp2pattribute_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cumoduleloaddata_1(mem_data mem, ptr_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cuModuleLoadData,
		(xdrproc_t) xdr_mem_data, (caddr_t) &mem,
		(xdrproc_t) xdr_ptr_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cusolverdncreate_1(ptr_result *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, rpc_cusolverDnCreate, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_ptr_result, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
rpc_cusolverdnsetstream_1(ptr arg1, ptr arg2, int *clnt_res,  CLIENT *clnt)
{
	rpc_cusolverdnsetstream_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	return (clnt_call (clnt, rpc_cusolverDnSetStream, (xdrproc_t) xdr_rpc_cusolverdnsetstream_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cusolverdndgetrf_buffersize_1(ptr arg1, int arg2, int arg3, ptr arg4, int arg5, int_result *clnt_res,  CLIENT *clnt)
{
	rpc_cusolverdndgetrf_buffersize_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	arg.arg4 = arg4;
	arg.arg5 = arg5;
	return (clnt_call (clnt, rpc_cusolverDnDgetrf_bufferSize, (xdrproc_t) xdr_rpc_cusolverdndgetrf_buffersize_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cusolverdndgetrf_1(ptr arg1, int arg2, int arg3, ptr arg4, int arg5, ptr arg6, ptr arg7, ptr arg8, int *clnt_res,  CLIENT *clnt)
{
	rpc_cusolverdndgetrf_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	arg.arg4 = arg4;
	arg.arg5 = arg5;
	arg.arg6 = arg6;
	arg.arg7 = arg7;
	arg.arg8 = arg8;
	return (clnt_call (clnt, rpc_cusolverDnDgetrf, (xdrproc_t) xdr_rpc_cusolverdndgetrf_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cusolverdndgetrs_1(ptr arg1, int arg2, int arg3, int arg4, ptr arg5, int arg6, ptr arg7, ptr arg8, int arg9, ptr arg10, int *clnt_res,  CLIENT *clnt)
{
	rpc_cusolverdndgetrs_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	arg.arg4 = arg4;
	arg.arg5 = arg5;
	arg.arg6 = arg6;
	arg.arg7 = arg7;
	arg.arg8 = arg8;
	arg.arg9 = arg9;
	arg.arg10 = arg10;
	return (clnt_call (clnt, rpc_cusolverDnDgetrs, (xdrproc_t) xdr_rpc_cusolverdndgetrs_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cusolverdndestroy_1(ptr arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cusolverDnDestroy,
		(xdrproc_t) xdr_ptr, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cublascreate_1(ptr_result *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, rpc_cublasCreate, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_ptr_result, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
rpc_cublasdgemm_1(ptr arg1, int arg2, int arg3, int arg4, int arg5, int arg6, double arg7, ptr arg8, int arg9, ptr arg10, int arg11, double arg12, ptr arg13, int arg14, int *clnt_res,  CLIENT *clnt)
{
	rpc_cublasdgemm_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	arg.arg4 = arg4;
	arg.arg5 = arg5;
	arg.arg6 = arg6;
	arg.arg7 = arg7;
	arg.arg8 = arg8;
	arg.arg9 = arg9;
	arg.arg10 = arg10;
	arg.arg11 = arg11;
	arg.arg12 = arg12;
	arg.arg13 = arg13;
	arg.arg14 = arg14;
	return (clnt_call (clnt, rpc_cublasDgemm, (xdrproc_t) xdr_rpc_cublasdgemm_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cublasdestroy_1(ptr arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cublasDestroy,
		(xdrproc_t) xdr_ptr, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cublassgemm_1(ptr arg1, int arg2, int arg3, int arg4, int arg5, int arg6, float arg7, ptr arg8, int arg9, ptr arg10, int arg11, float arg12, ptr arg13, int arg14, int *clnt_res,  CLIENT *clnt)
{
	rpc_cublassgemm_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	arg.arg4 = arg4;
	arg.arg5 = arg5;
	arg.arg6 = arg6;
	arg.arg7 = arg7;
	arg.arg8 = arg8;
	arg.arg9 = arg9;
	arg.arg10 = arg10;
	arg.arg11 = arg11;
	arg.arg12 = arg12;
	arg.arg13 = arg13;
	arg.arg14 = arg14;
	return (clnt_call (clnt, rpc_cublasSgemm, (xdrproc_t) xdr_rpc_cublassgemm_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cublassgemv_1(ptr arg1, int arg2, int arg3, int arg4, float arg5, ptr arg6, int arg7, ptr arg8, int arg9, float arg10, ptr arg11, int arg12, int *clnt_res,  CLIENT *clnt)
{
	rpc_cublassgemv_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	arg.arg4 = arg4;
	arg.arg5 = arg5;
	arg.arg6 = arg6;
	arg.arg7 = arg7;
	arg.arg8 = arg8;
	arg.arg9 = arg9;
	arg.arg10 = arg10;
	arg.arg11 = arg11;
	arg.arg12 = arg12;
	return (clnt_call (clnt, rpc_cublasSgemv, (xdrproc_t) xdr_rpc_cublassgemv_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cublasdgemv_1(ptr arg1, int arg2, int arg3, int arg4, double arg5, ptr arg6, int arg7, ptr arg8, int arg9, double arg10, ptr arg11, int arg12, int *clnt_res,  CLIENT *clnt)
{
	rpc_cublasdgemv_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	arg.arg4 = arg4;
	arg.arg5 = arg5;
	arg.arg6 = arg6;
	arg.arg7 = arg7;
	arg.arg8 = arg8;
	arg.arg9 = arg9;
	arg.arg10 = arg10;
	arg.arg11 = arg11;
	arg.arg12 = arg12;
	return (clnt_call (clnt, rpc_cublasDgemv, (xdrproc_t) xdr_rpc_cublasdgemv_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cublassgemmex_1(ptr arg1, int arg2, int arg3, int arg4, int arg5, int arg6, float arg7, ptr arg8, int arg9, int arg10, ptr arg11, int arg12, int arg13, float arg14, ptr arg15, int arg16, int arg17, int *clnt_res,  CLIENT *clnt)
{
	rpc_cublassgemmex_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	arg.arg4 = arg4;
	arg.arg5 = arg5;
	arg.arg6 = arg6;
	arg.arg7 = arg7;
	arg.arg8 = arg8;
	arg.arg9 = arg9;
	arg.arg10 = arg10;
	arg.arg11 = arg11;
	arg.arg12 = arg12;
	arg.arg13 = arg13;
	arg.arg14 = arg14;
	arg.arg15 = arg15;
	arg.arg16 = arg16;
	arg.arg17 = arg17;
	return (clnt_call (clnt, rpc_cublasSgemmEx, (xdrproc_t) xdr_rpc_cublassgemmex_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cublassetstream_1(ptr handle, ptr streamId, int *clnt_res,  CLIENT *clnt)
{
	rpc_cublassetstream_1_argument arg;
	arg.handle = handle;
	arg.streamId = streamId;
	return (clnt_call (clnt, rpc_cublasSetStream, (xdrproc_t) xdr_rpc_cublassetstream_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cublassetworkspace_1(ptr handle, ptr workspace, size_t workspaceSizeInBytes, int *clnt_res,  CLIENT *clnt)
{
	rpc_cublassetworkspace_1_argument arg;
	arg.handle = handle;
	arg.workspace = workspace;
	arg.workspaceSizeInBytes = workspaceSizeInBytes;
	return (clnt_call (clnt, rpc_cublasSetWorkspace, (xdrproc_t) xdr_rpc_cublassetworkspace_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cublassetmathmode_1(ptr handle, int mode, int *clnt_res,  CLIENT *clnt)
{
	rpc_cublassetmathmode_1_argument arg;
	arg.handle = handle;
	arg.mode = mode;
	return (clnt_call (clnt, rpc_cublasSetMathMode, (xdrproc_t) xdr_rpc_cublassetmathmode_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_nvmldevicegetcount_v2_1(int_result *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, rpc_nvmlDeviceGetCount_v2, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int_result, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
rpc_nvmlinitwithflags_1(int arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_nvmlInitWithFlags,
		(xdrproc_t) xdr_int, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_nvmlinit_v2_1(int *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, rpc_nvmlInit_v2, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
rpc_nvmlshutdown_1(int *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, rpc_nvmlShutdown, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
rpc_cudnngetversion_1(size_t *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, rpc_cudnnGetVersion, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_size_t, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
rpc_cudnngetmaxdeviceversion_1(size_t *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, rpc_cudnnGetMaxDeviceVersion, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_size_t, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
rpc_cudnngetcudartversion_1(size_t *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, rpc_cudnnGetCudartVersion, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_size_t, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
rpc_cudnngeterrorstring_1(int status, char **clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cudnnGetErrorString,
		(xdrproc_t) xdr_int, (caddr_t) &status,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnnqueryruntimeerror_1(ptr handle, int mode, int_result *clnt_res,  CLIENT *clnt)
{
	rpc_cudnnqueryruntimeerror_1_argument arg;
	arg.handle = handle;
	arg.mode = mode;
	return (clnt_call (clnt, rpc_cudnnQueryRuntimeError, (xdrproc_t) xdr_rpc_cudnnqueryruntimeerror_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnngetproperty_1(int type, int_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cudnnGetProperty,
		(xdrproc_t) xdr_int, (caddr_t) &type,
		(xdrproc_t) xdr_int_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnncreate_1(ptr_result *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, rpc_cudnnCreate, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_ptr_result, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
rpc_cudnndestroy_1(ptr handle, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cudnnDestroy,
		(xdrproc_t) xdr_ptr, (caddr_t) &handle,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnnsetstream_1(ptr handle, ptr streamId, int *clnt_res,  CLIENT *clnt)
{
	rpc_cudnnsetstream_1_argument arg;
	arg.handle = handle;
	arg.streamId = streamId;
	return (clnt_call (clnt, rpc_cudnnSetStream, (xdrproc_t) xdr_rpc_cudnnsetstream_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnngetstream_1(ptr handle, ptr_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cudnnGetStream,
		(xdrproc_t) xdr_ptr, (caddr_t) &handle,
		(xdrproc_t) xdr_ptr_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnncreatetensordescriptor_1(ptr_result *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, rpc_cudnnCreateTensorDescriptor, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_ptr_result, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
rpc_cudnnsettensor4ddescriptor_1(ptr tensorDesc, int format, int dataType, int n, int c, int h, int w, int *clnt_res,  CLIENT *clnt)
{
	rpc_cudnnsettensor4ddescriptor_1_argument arg;
	arg.tensorDesc = tensorDesc;
	arg.format = format;
	arg.dataType = dataType;
	arg.n = n;
	arg.c = c;
	arg.h = h;
	arg.w = w;
	return (clnt_call (clnt, rpc_cudnnSetTensor4dDescriptor, (xdrproc_t) xdr_rpc_cudnnsettensor4ddescriptor_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnnsettensor4ddescriptorex_1(ptr tensorDesc, int dataType, int n, int c, int h, int w, int nStride, int cStride, int hStride, int wStride, int *clnt_res,  CLIENT *clnt)
{
	rpc_cudnnsettensor4ddescriptorex_1_argument arg;
	arg.tensorDesc = tensorDesc;
	arg.dataType = dataType;
	arg.n = n;
	arg.c = c;
	arg.h = h;
	arg.w = w;
	arg.nStride = nStride;
	arg.cStride = cStride;
	arg.hStride = hStride;
	arg.wStride = wStride;
	return (clnt_call (clnt, rpc_cudnnSetTensor4dDescriptorEx, (xdrproc_t) xdr_rpc_cudnnsettensor4ddescriptorex_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnngettensor4ddescriptor_1(ptr tensorDesc, int9_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cudnnGetTensor4dDescriptor,
		(xdrproc_t) xdr_ptr, (caddr_t) &tensorDesc,
		(xdrproc_t) xdr_int9_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnnsettensornddescriptor_1(ptr tensorDesc, int dataType, int nbDims, mem_data dimA, mem_data strideA, int *clnt_res,  CLIENT *clnt)
{
	rpc_cudnnsettensornddescriptor_1_argument arg;
	arg.tensorDesc = tensorDesc;
	arg.dataType = dataType;
	arg.nbDims = nbDims;
	arg.dimA = dimA;
	arg.strideA = strideA;
	return (clnt_call (clnt, rpc_cudnnSetTensorNdDescriptor, (xdrproc_t) xdr_rpc_cudnnsettensornddescriptor_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnnsettensornddescriptorex_1(ptr tensorDesc, int format, int dataType, int nbDims, mem_data dimA, int *clnt_res,  CLIENT *clnt)
{
	rpc_cudnnsettensornddescriptorex_1_argument arg;
	arg.tensorDesc = tensorDesc;
	arg.format = format;
	arg.dataType = dataType;
	arg.nbDims = nbDims;
	arg.dimA = dimA;
	return (clnt_call (clnt, rpc_cudnnSetTensorNdDescriptorEx, (xdrproc_t) xdr_rpc_cudnnsettensornddescriptorex_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnngettensornddescriptor_1(ptr tensorDesc, int nbDimsRequested, mem_result *clnt_res,  CLIENT *clnt)
{
	rpc_cudnngettensornddescriptor_1_argument arg;
	arg.tensorDesc = tensorDesc;
	arg.nbDimsRequested = nbDimsRequested;
	return (clnt_call (clnt, rpc_cudnnGetTensorNdDescriptor, (xdrproc_t) xdr_rpc_cudnngettensornddescriptor_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_mem_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnngettensorsizeinbytes_1(ptr tensorDesc, sz_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cudnnGetTensorSizeInBytes,
		(xdrproc_t) xdr_ptr, (caddr_t) &tensorDesc,
		(xdrproc_t) xdr_sz_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnndestroytensordescriptor_1(ptr tensorDesc, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cudnnDestroyTensorDescriptor,
		(xdrproc_t) xdr_ptr, (caddr_t) &tensorDesc,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnntransformtensor_1(ptr handle, cudnn_scaling_t alpha, ptr xDesc, ptr x, cudnn_scaling_t beta, ptr yDesc, ptr y, int *clnt_res,  CLIENT *clnt)
{
	rpc_cudnntransformtensor_1_argument arg;
	arg.handle = handle;
	arg.alpha = alpha;
	arg.xDesc = xDesc;
	arg.x = x;
	arg.beta = beta;
	arg.yDesc = yDesc;
	arg.y = y;
	return (clnt_call (clnt, rpc_cudnnTransformTensor, (xdrproc_t) xdr_rpc_cudnntransformtensor_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnnaddtensor_1(ptr handle, cudnn_scaling_t alpha, ptr aDesc, ptr A, cudnn_scaling_t beta, ptr cDesc, ptr C, int *clnt_res,  CLIENT *clnt)
{
	rpc_cudnnaddtensor_1_argument arg;
	arg.handle = handle;
	arg.alpha = alpha;
	arg.aDesc = aDesc;
	arg.A = A;
	arg.beta = beta;
	arg.cDesc = cDesc;
	arg.C = C;
	return (clnt_call (clnt, rpc_cudnnAddTensor, (xdrproc_t) xdr_rpc_cudnnaddtensor_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnncreatefilterdescriptor_1(ptr_result *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, rpc_cudnnCreateFilterDescriptor, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_ptr_result, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
rpc_cudnnsetfilter4ddescriptor_1(ptr filterDesc, int dataType, int format, int k, int c, int h, int w, int *clnt_res,  CLIENT *clnt)
{
	rpc_cudnnsetfilter4ddescriptor_1_argument arg;
	arg.filterDesc = filterDesc;
	arg.dataType = dataType;
	arg.format = format;
	arg.k = k;
	arg.c = c;
	arg.h = h;
	arg.w = w;
	return (clnt_call (clnt, rpc_cudnnSetFilter4dDescriptor, (xdrproc_t) xdr_rpc_cudnnsetfilter4ddescriptor_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnngetfilter4ddescriptor_1(ptr filterDesc, int6_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cudnnGetFilter4dDescriptor,
		(xdrproc_t) xdr_ptr, (caddr_t) &filterDesc,
		(xdrproc_t) xdr_int6_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnnsetfilternddescriptor_1(ptr filterDesc, int dataType, int format, int nbDims, mem_data filterDimA, int *clnt_res,  CLIENT *clnt)
{
	rpc_cudnnsetfilternddescriptor_1_argument arg;
	arg.filterDesc = filterDesc;
	arg.dataType = dataType;
	arg.format = format;
	arg.nbDims = nbDims;
	arg.filterDimA = filterDimA;
	return (clnt_call (clnt, rpc_cudnnSetFilterNdDescriptor, (xdrproc_t) xdr_rpc_cudnnsetfilternddescriptor_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnngetfilternddescriptor_1(ptr filterDesc, int nbDimsRequested, mem_result *clnt_res,  CLIENT *clnt)
{
	rpc_cudnngetfilternddescriptor_1_argument arg;
	arg.filterDesc = filterDesc;
	arg.nbDimsRequested = nbDimsRequested;
	return (clnt_call (clnt, rpc_cudnnGetFilterNdDescriptor, (xdrproc_t) xdr_rpc_cudnngetfilternddescriptor_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_mem_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnngetfiltersizeinbytes_1(ptr filterDesc, sz_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cudnnGetFilterSizeInBytes,
		(xdrproc_t) xdr_ptr, (caddr_t) &filterDesc,
		(xdrproc_t) xdr_sz_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnntransformfilter_1(ptr handle, ptr transDesc, cudnn_scaling_t alpha, ptr srcDesc, ptr srcData, cudnn_scaling_t beta, ptr destDesc, ptr destData, int *clnt_res,  CLIENT *clnt)
{
	rpc_cudnntransformfilter_1_argument arg;
	arg.handle = handle;
	arg.transDesc = transDesc;
	arg.alpha = alpha;
	arg.srcDesc = srcDesc;
	arg.srcData = srcData;
	arg.beta = beta;
	arg.destDesc = destDesc;
	arg.destData = destData;
	return (clnt_call (clnt, rpc_cudnnTransformFilter, (xdrproc_t) xdr_rpc_cudnntransformfilter_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnndestroyfilterdescriptor_1(ptr filterDesc, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cudnnDestroyFilterDescriptor,
		(xdrproc_t) xdr_ptr, (caddr_t) &filterDesc,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnnsoftmaxforward_1(ptr handle, int algo, int mode, cudnn_scaling_t alpha, ptr xDesc, ptr x, cudnn_scaling_t beta, ptr yDesc, ptr y, int *clnt_res,  CLIENT *clnt)
{
	rpc_cudnnsoftmaxforward_1_argument arg;
	arg.handle = handle;
	arg.algo = algo;
	arg.mode = mode;
	arg.alpha = alpha;
	arg.xDesc = xDesc;
	arg.x = x;
	arg.beta = beta;
	arg.yDesc = yDesc;
	arg.y = y;
	return (clnt_call (clnt, rpc_cudnnSoftmaxForward, (xdrproc_t) xdr_rpc_cudnnsoftmaxforward_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnncreatepoolingdescriptor_1(ptr_result *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, rpc_cudnnCreatePoolingDescriptor, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_ptr_result, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
rpc_cudnnsetpooling2ddescriptor_1(ptr poolingDesc, int mode, int maxpoolingNanOpt, int windowHeight, int windowWidth, int verticalPadding, int horizontalPadding, int verticalStride, int horizontalStride, int *clnt_res,  CLIENT *clnt)
{
	rpc_cudnnsetpooling2ddescriptor_1_argument arg;
	arg.poolingDesc = poolingDesc;
	arg.mode = mode;
	arg.maxpoolingNanOpt = maxpoolingNanOpt;
	arg.windowHeight = windowHeight;
	arg.windowWidth = windowWidth;
	arg.verticalPadding = verticalPadding;
	arg.horizontalPadding = horizontalPadding;
	arg.verticalStride = verticalStride;
	arg.horizontalStride = horizontalStride;
	return (clnt_call (clnt, rpc_cudnnSetPooling2dDescriptor, (xdrproc_t) xdr_rpc_cudnnsetpooling2ddescriptor_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnngetpooling2ddescriptor_1(ptr poolingDesc, int8_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cudnnGetPooling2dDescriptor,
		(xdrproc_t) xdr_ptr, (caddr_t) &poolingDesc,
		(xdrproc_t) xdr_int8_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnnsetpoolingnddescriptor_1(ptr poolingDesc, int mode, int maxpoolingNanOpt, int nbDims, mem_data windowDimA, mem_data paddingA, mem_data strideA, int *clnt_res,  CLIENT *clnt)
{
	rpc_cudnnsetpoolingnddescriptor_1_argument arg;
	arg.poolingDesc = poolingDesc;
	arg.mode = mode;
	arg.maxpoolingNanOpt = maxpoolingNanOpt;
	arg.nbDims = nbDims;
	arg.windowDimA = windowDimA;
	arg.paddingA = paddingA;
	arg.strideA = strideA;
	return (clnt_call (clnt, rpc_cudnnSetPoolingNdDescriptor, (xdrproc_t) xdr_rpc_cudnnsetpoolingnddescriptor_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnngetpoolingnddescriptor_1(ptr poolingDesc, int nbDimsRequested, mem_result *clnt_res,  CLIENT *clnt)
{
	rpc_cudnngetpoolingnddescriptor_1_argument arg;
	arg.poolingDesc = poolingDesc;
	arg.nbDimsRequested = nbDimsRequested;
	return (clnt_call (clnt, rpc_cudnnGetPoolingNdDescriptor, (xdrproc_t) xdr_rpc_cudnngetpoolingnddescriptor_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_mem_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnngetpoolingndforwardoutputdim_1(ptr poolingDesc, ptr inputTensorDesc, int nbDims, mem_result *clnt_res,  CLIENT *clnt)
{
	rpc_cudnngetpoolingndforwardoutputdim_1_argument arg;
	arg.poolingDesc = poolingDesc;
	arg.inputTensorDesc = inputTensorDesc;
	arg.nbDims = nbDims;
	return (clnt_call (clnt, rpc_cudnnGetPoolingNdForwardOutputDim, (xdrproc_t) xdr_rpc_cudnngetpoolingndforwardoutputdim_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_mem_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnngetpooling2dforwardoutputdim_1(ptr poolingDesc, ptr inputTensorDesc, int4_result *clnt_res,  CLIENT *clnt)
{
	rpc_cudnngetpooling2dforwardoutputdim_1_argument arg;
	arg.poolingDesc = poolingDesc;
	arg.inputTensorDesc = inputTensorDesc;
	return (clnt_call (clnt, rpc_cudnnGetPooling2dForwardOutputDim, (xdrproc_t) xdr_rpc_cudnngetpooling2dforwardoutputdim_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int4_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnndestroypoolingdescriptor_1(ptr poolingDesc, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cudnnDestroyPoolingDescriptor,
		(xdrproc_t) xdr_ptr, (caddr_t) &poolingDesc,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnnpoolingforward_1(ptr handle, ptr poolingDesc, cudnn_scaling_t alpha, ptr xDesc, ptr x, cudnn_scaling_t beta, ptr yDesc, ptr y, int *clnt_res,  CLIENT *clnt)
{
	rpc_cudnnpoolingforward_1_argument arg;
	arg.handle = handle;
	arg.poolingDesc = poolingDesc;
	arg.alpha = alpha;
	arg.xDesc = xDesc;
	arg.x = x;
	arg.beta = beta;
	arg.yDesc = yDesc;
	arg.y = y;
	return (clnt_call (clnt, rpc_cudnnPoolingForward, (xdrproc_t) xdr_rpc_cudnnpoolingforward_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnncreateactivationdescriptor_1(ptr_result *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, rpc_cudnnCreateActivationDescriptor, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_ptr_result, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
rpc_cudnnsetactivationdescriptor_1(ptr activationDesc, int mode, int reluNanOpt, double coef, int *clnt_res,  CLIENT *clnt)
{
	rpc_cudnnsetactivationdescriptor_1_argument arg;
	arg.activationDesc = activationDesc;
	arg.mode = mode;
	arg.reluNanOpt = reluNanOpt;
	arg.coef = coef;
	return (clnt_call (clnt, rpc_cudnnSetActivationDescriptor, (xdrproc_t) xdr_rpc_cudnnsetactivationdescriptor_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnngetactivationdescriptor_1(ptr activationDesc, int2d1_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cudnnGetActivationDescriptor,
		(xdrproc_t) xdr_ptr, (caddr_t) &activationDesc,
		(xdrproc_t) xdr_int2d1_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnnsetactivationdescriptorswishbeta_1(ptr activationDesc, double swish_beta, int *clnt_res,  CLIENT *clnt)
{
	rpc_cudnnsetactivationdescriptorswishbeta_1_argument arg;
	arg.activationDesc = activationDesc;
	arg.swish_beta = swish_beta;
	return (clnt_call (clnt, rpc_cudnnSetActivationDescriptorSwishBeta, (xdrproc_t) xdr_rpc_cudnnsetactivationdescriptorswishbeta_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnngetactivationdescriptorswishbeta_1(ptr activationDesc, d_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cudnnGetActivationDescriptorSwishBeta,
		(xdrproc_t) xdr_ptr, (caddr_t) &activationDesc,
		(xdrproc_t) xdr_d_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnndestroyactivationdescriptor_1(ptr activationDesc, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cudnnDestroyActivationDescriptor,
		(xdrproc_t) xdr_ptr, (caddr_t) &activationDesc,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnnactivationforward_1(ptr handle, ptr activationDesc, cudnn_scaling_t alpha, ptr xDesc, ptr x, cudnn_scaling_t beta, ptr yDesc, ptr y, int *clnt_res,  CLIENT *clnt)
{
	rpc_cudnnactivationforward_1_argument arg;
	arg.handle = handle;
	arg.activationDesc = activationDesc;
	arg.alpha = alpha;
	arg.xDesc = xDesc;
	arg.x = x;
	arg.beta = beta;
	arg.yDesc = yDesc;
	arg.y = y;
	return (clnt_call (clnt, rpc_cudnnActivationForward, (xdrproc_t) xdr_rpc_cudnnactivationforward_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnncreatelrndescriptor_1(ptr_result *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, rpc_cudnnCreateLRNDescriptor, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_ptr_result, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
rpc_cudnnsetlrndescriptor_1(ptr normDesc, u_int lrnN, double lrnAlpha, double lrnBeta, double lrnK, int *clnt_res,  CLIENT *clnt)
{
	rpc_cudnnsetlrndescriptor_1_argument arg;
	arg.normDesc = normDesc;
	arg.lrnN = lrnN;
	arg.lrnAlpha = lrnAlpha;
	arg.lrnBeta = lrnBeta;
	arg.lrnK = lrnK;
	return (clnt_call (clnt, rpc_cudnnSetLRNDescriptor, (xdrproc_t) xdr_rpc_cudnnsetlrndescriptor_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnngetlrndescriptor_1(ptr normDesc, int1d3_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cudnnGetLRNDescriptor,
		(xdrproc_t) xdr_ptr, (caddr_t) &normDesc,
		(xdrproc_t) xdr_int1d3_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnndestroylrndescriptor_1(ptr lrnDesc, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cudnnDestroyLRNDescriptor,
		(xdrproc_t) xdr_ptr, (caddr_t) &lrnDesc,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnnlrncrosschannelforward_1(ptr handle, ptr normDesc, int lrnMode, cudnn_scaling_t alpha, ptr xDesc, ptr x, cudnn_scaling_t beta, ptr yDesc, ptr y, int *clnt_res,  CLIENT *clnt)
{
	rpc_cudnnlrncrosschannelforward_1_argument arg;
	arg.handle = handle;
	arg.normDesc = normDesc;
	arg.lrnMode = lrnMode;
	arg.alpha = alpha;
	arg.xDesc = xDesc;
	arg.x = x;
	arg.beta = beta;
	arg.yDesc = yDesc;
	arg.y = y;
	return (clnt_call (clnt, rpc_cudnnLRNCrossChannelForward, (xdrproc_t) xdr_rpc_cudnnlrncrosschannelforward_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnncreateconvolutiondescriptor_1(ptr_result *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, rpc_cudnnCreateConvolutionDescriptor, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_ptr_result, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
rpc_cudnndestroyconvolutiondescriptor_1(ptr convDesc, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cudnnDestroyConvolutionDescriptor,
		(xdrproc_t) xdr_ptr, (caddr_t) &convDesc,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnngetconvolutionndforwardoutputdim_1(ptr convDesc, ptr inputTensorDesc, ptr filterDesc, int nbDims, mem_result *clnt_res,  CLIENT *clnt)
{
	rpc_cudnngetconvolutionndforwardoutputdim_1_argument arg;
	arg.convDesc = convDesc;
	arg.inputTensorDesc = inputTensorDesc;
	arg.filterDesc = filterDesc;
	arg.nbDims = nbDims;
	return (clnt_call (clnt, rpc_cudnnGetConvolutionNdForwardOutputDim, (xdrproc_t) xdr_rpc_cudnngetconvolutionndforwardoutputdim_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_mem_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnnsetconvolutionnddescriptor_1(ptr convDesc, int arrayLength, mem_data padA, mem_data filterStrideA, mem_data dilationA, int mode, int computeType, int *clnt_res,  CLIENT *clnt)
{
	rpc_cudnnsetconvolutionnddescriptor_1_argument arg;
	arg.convDesc = convDesc;
	arg.arrayLength = arrayLength;
	arg.padA = padA;
	arg.filterStrideA = filterStrideA;
	arg.dilationA = dilationA;
	arg.mode = mode;
	arg.computeType = computeType;
	return (clnt_call (clnt, rpc_cudnnSetConvolutionNdDescriptor, (xdrproc_t) xdr_rpc_cudnnsetconvolutionnddescriptor_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnngetconvolutionforwardalgorithm_v7_1(ptr handle, ptr srcDesc, ptr filterDesc, ptr convDesc, ptr destDesc, int requestedAlgoCount, mem_result *clnt_res,  CLIENT *clnt)
{
	rpc_cudnngetconvolutionforwardalgorithm_v7_1_argument arg;
	arg.handle = handle;
	arg.srcDesc = srcDesc;
	arg.filterDesc = filterDesc;
	arg.convDesc = convDesc;
	arg.destDesc = destDesc;
	arg.requestedAlgoCount = requestedAlgoCount;
	return (clnt_call (clnt, rpc_cudnnGetConvolutionForwardAlgorithm_v7, (xdrproc_t) xdr_rpc_cudnngetconvolutionforwardalgorithm_v7_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_mem_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnnfindconvolutionforwardalgorithm_1(ptr handle, ptr xDesc, ptr wDesc, ptr convDesc, ptr yDesc, int requestedAlgoCount, mem_result *clnt_res,  CLIENT *clnt)
{
	rpc_cudnnfindconvolutionforwardalgorithm_1_argument arg;
	arg.handle = handle;
	arg.xDesc = xDesc;
	arg.wDesc = wDesc;
	arg.convDesc = convDesc;
	arg.yDesc = yDesc;
	arg.requestedAlgoCount = requestedAlgoCount;
	return (clnt_call (clnt, rpc_cudnnFindConvolutionForwardAlgorithm, (xdrproc_t) xdr_rpc_cudnnfindconvolutionforwardalgorithm_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_mem_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnngetconvolutionforwardworkspacesize_1(ptr handle, ptr xDesc, ptr wDesc, ptr convDesc, ptr yDesc, int algo, sz_result *clnt_res,  CLIENT *clnt)
{
	rpc_cudnngetconvolutionforwardworkspacesize_1_argument arg;
	arg.handle = handle;
	arg.xDesc = xDesc;
	arg.wDesc = wDesc;
	arg.convDesc = convDesc;
	arg.yDesc = yDesc;
	arg.algo = algo;
	return (clnt_call (clnt, rpc_cudnnGetConvolutionForwardWorkspaceSize, (xdrproc_t) xdr_rpc_cudnngetconvolutionforwardworkspacesize_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_sz_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnnconvolutionforward_1(ptr handle, cudnn_scaling_t alpha, ptr xDesc, ptr x, ptr wDesc, ptr w, ptr convDesc, int algo, ptr workSpace, size_t workSpaceSizeInBytes, cudnn_scaling_t beta, ptr yDesc, ptr y, int *clnt_res,  CLIENT *clnt)
{
	rpc_cudnnconvolutionforward_1_argument arg;
	arg.handle = handle;
	arg.alpha = alpha;
	arg.xDesc = xDesc;
	arg.x = x;
	arg.wDesc = wDesc;
	arg.w = w;
	arg.convDesc = convDesc;
	arg.algo = algo;
	arg.workSpace = workSpace;
	arg.workSpaceSizeInBytes = workSpaceSizeInBytes;
	arg.beta = beta;
	arg.yDesc = yDesc;
	arg.y = y;
	return (clnt_call (clnt, rpc_cudnnConvolutionForward, (xdrproc_t) xdr_rpc_cudnnconvolutionforward_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnnbackendcreatedescriptor_1(int descriptorType, ptr_result *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cudnnBackendCreateDescriptor,
		(xdrproc_t) xdr_int, (caddr_t) &descriptorType,
		(xdrproc_t) xdr_ptr_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnnbackenddestroydescriptor_1(ptr descriptor, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cudnnBackendDestroyDescriptor,
		(xdrproc_t) xdr_ptr, (caddr_t) &descriptor,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnnbackendinitialize_1(ptr descriptor, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cudnnBackendInitialize,
		(xdrproc_t) xdr_ptr, (caddr_t) &descriptor,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnnbackendfinalize_1(ptr descriptor, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_cudnnBackendFinalize,
		(xdrproc_t) xdr_ptr, (caddr_t) &descriptor,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnnbackendsetattribute_1(ptr descriptor, int attributeName, int attributeType, quad_t elementCount, mem_data arrayOfElements, int *clnt_res,  CLIENT *clnt)
{
	rpc_cudnnbackendsetattribute_1_argument arg;
	arg.descriptor = descriptor;
	arg.attributeName = attributeName;
	arg.attributeType = attributeType;
	arg.elementCount = elementCount;
	arg.arrayOfElements = arrayOfElements;
	return (clnt_call (clnt, rpc_cudnnBackendSetAttribute, (xdrproc_t) xdr_rpc_cudnnbackendsetattribute_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnnbackendgetattribute_1(ptr descriptor, int attributeName, int attributeType, quad_t requestedElementCount, mem_result *clnt_res,  CLIENT *clnt)
{
	rpc_cudnnbackendgetattribute_1_argument arg;
	arg.descriptor = descriptor;
	arg.attributeName = attributeName;
	arg.attributeType = attributeType;
	arg.requestedElementCount = requestedElementCount;
	return (clnt_call (clnt, rpc_cudnnBackendGetAttribute, (xdrproc_t) xdr_rpc_cudnnbackendgetattribute_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_mem_result, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_cudnnbackendexecute_1(ptr handle, ptr executionPlan, ptr variantPack, int *clnt_res,  CLIENT *clnt)
{
	rpc_cudnnbackendexecute_1_argument arg;
	arg.handle = handle;
	arg.executionPlan = executionPlan;
	arg.variantPack = variantPack;
	return (clnt_call (clnt, rpc_cudnnBackendExecute, (xdrproc_t) xdr_rpc_cudnnbackendexecute_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
