/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "cpu_rpc_prot.h"

bool_t
xdr_mem_data (XDR *xdrs, mem_data *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->mem_data_val, (u_int *) &objp->mem_data_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_size_t (XDR *xdrs, size_t *objp)
{
	register int32_t *buf;

	 if (!xdr_u_quad_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ptr (XDR *xdrs, ptr *objp)
{
	register int32_t *buf;

	 if (!xdr_u_quad_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cuda_device_prop (XDR *xdrs, rpc_cuda_device_prop objp)
{
	register int32_t *buf;

	 if (!xdr_opaque (xdrs, objp, 1032))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_dint (XDR *xdrs, dint *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->i1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->i2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_dsz (XDR *xdrs, dsz *objp)
{
	register int32_t *buf;

	 if (!xdr_size_t (xdrs, &objp->sz1))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->sz2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ptrsz (XDR *xdrs, ptrsz *objp)
{
	register int32_t *buf;

	 if (!xdr_ptr (xdrs, &objp->p))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->s))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_channel_format_desc (XDR *xdrs, cuda_channel_format_desc *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->f))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->w))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->x))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->y))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->z))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->f);
			IXDR_PUT_LONG(buf, objp->w);
			IXDR_PUT_LONG(buf, objp->x);
			IXDR_PUT_LONG(buf, objp->y);
			IXDR_PUT_LONG(buf, objp->z);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->f))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->w))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->x))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->y))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->z))
				 return FALSE;
		} else {
			objp->f = IXDR_GET_LONG(buf);
			objp->w = IXDR_GET_LONG(buf);
			objp->x = IXDR_GET_LONG(buf);
			objp->y = IXDR_GET_LONG(buf);
			objp->z = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->f))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->w))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->z))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_pitche_ptr (XDR *xdrs, pitche_ptr *objp)
{
	register int32_t *buf;

	 if (!xdr_size_t (xdrs, &objp->pitch))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->ptr))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->xsize))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->ysize))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_dim3 (XDR *xdrs, rpc_dim3 *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->y))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->z))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_int2d1 (XDR *xdrs, int2d1 *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, ( 2 ) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->i, 2,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;

		} else {
		{
			register int *genp;

			for (i = 0, genp = objp->i;
				i < 2; ++i) {
				IXDR_PUT_LONG(buf, *genp++);
			}
		}
		}
		 if (!xdr_double (xdrs, &objp->d))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, ( 2 ) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->i, 2,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;

		} else {
		{
			register int *genp;

			for (i = 0, genp = objp->i;
				i < 2; ++i) {
				*genp++ = IXDR_GET_LONG(buf);
			}
		}
		}
		 if (!xdr_double (xdrs, &objp->d))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->i, 2,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->d))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_int1d3 (XDR *xdrs, int1d3 *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->i))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->d, 3,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cudnn_scaling_t (XDR *xdrs, cudnn_scaling_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->dataType))
		 return FALSE;
	switch (objp->dataType) {
	case 2:
	case 0:
		 if (!xdr_float (xdrs, &objp->cudnn_scaling_t_u.f))
			 return FALSE;
		break;
	case 1:
		 if (!xdr_double (xdrs, &objp->cudnn_scaling_t_u.d))
			 return FALSE;
		break;
	default:
		return FALSE;
	}
	return TRUE;
}

bool_t
xdr_int_result (XDR *xdrs, int_result *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_int (xdrs, &objp->int_result_u.data))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_dint_result (XDR *xdrs, dint_result *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_dint (xdrs, &objp->dint_result_u.data))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_float_result (XDR *xdrs, float_result *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_float (xdrs, &objp->float_result_u.data))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_d_result (XDR *xdrs, d_result *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_double (xdrs, &objp->d_result_u.data))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_u64_result (XDR *xdrs, u64_result *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_u_quad_t (xdrs, &objp->u64_result_u.u64))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_dsz_result (XDR *xdrs, dsz_result *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_dsz (xdrs, &objp->dsz_result_u.data))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_sz_result (XDR *xdrs, sz_result *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_size_t (xdrs, &objp->sz_result_u.data))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_ptr_result (XDR *xdrs, ptr_result *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_ptr (xdrs, &objp->ptr_result_u.ptr))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_pptr_result (XDR *xdrs, pptr_result *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_pitche_ptr (xdrs, &objp->pptr_result_u.ptr))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_str_result (XDR *xdrs, str_result *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_string (xdrs, &objp->str_result_u.str, 128))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_ptrsz_result (XDR *xdrs, ptrsz_result *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_ptrsz (xdrs, &objp->ptrsz_result_u.data))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_mem_result (XDR *xdrs, mem_result *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_mem_data (xdrs, &objp->mem_result_u.data))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_cuda_device_prop_result (XDR *xdrs, cuda_device_prop_result *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_rpc_cuda_device_prop (xdrs, objp->cuda_device_prop_result_u.data))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_int3_result (XDR *xdrs, int3_result *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_vector (xdrs, (char *)objp->int3_result_u.data, 3,
			sizeof (int), (xdrproc_t) xdr_int))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_int4_result (XDR *xdrs, int4_result *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_vector (xdrs, (char *)objp->int4_result_u.data, 4,
			sizeof (int), (xdrproc_t) xdr_int))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_int5_result (XDR *xdrs, int5_result *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_vector (xdrs, (char *)objp->int5_result_u.data, 5,
			sizeof (int), (xdrproc_t) xdr_int))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_int6_result (XDR *xdrs, int6_result *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_vector (xdrs, (char *)objp->int6_result_u.data, 6,
			sizeof (int), (xdrproc_t) xdr_int))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_int8_result (XDR *xdrs, int8_result *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_vector (xdrs, (char *)objp->int8_result_u.data, 8,
			sizeof (int), (xdrproc_t) xdr_int))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_int9_result (XDR *xdrs, int9_result *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_vector (xdrs, (char *)objp->int9_result_u.data, 9,
			sizeof (int), (xdrproc_t) xdr_int))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_int2d1_result (XDR *xdrs, int2d1_result *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_int2d1 (xdrs, &objp->int2d1_result_u.data))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_int1d3_result (XDR *xdrs, int1d3_result *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_int1d3 (xdrs, &objp->int1d3_result_u.data))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_rpc_register_function_1_argument (XDR *xdrs, rpc_register_function_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->arg3, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->arg4, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg5))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg6))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_elf_load_1_argument (XDR *xdrs, rpc_elf_load_1_argument *objp)
{
	 if (!xdr_mem_data (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_register_var_1_argument (XDR *xdrs, rpc_register_var_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg3))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->arg4, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg5))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg6))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg7))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg8))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg9))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_device_get_attribute_1_argument (XDR *xdrs, cuda_device_get_attribute_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_device_get_p2p_attribute_1_argument (XDR *xdrs, cuda_device_get_p2p_attribute_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_device_get_pci_bus_id_1_argument (XDR *xdrs, cuda_device_get_pci_bus_id_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_device_get_texture_lmw_1_argument (XDR *xdrs, cuda_device_get_texture_lmw_1_argument *objp)
{
	 if (!xdr_cuda_channel_format_desc (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_device_set_limit_1_argument (XDR *xdrs, cuda_device_set_limit_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_set_valid_devices_1_argument (XDR *xdrs, cuda_set_valid_devices_1_argument *objp)
{
	 if (!xdr_mem_data (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_stream_copy_attributes_1_argument (XDR *xdrs, cuda_stream_copy_attributes_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_stream_create_with_priority_1_argument (XDR *xdrs, cuda_stream_create_with_priority_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_stream_wait_event_1_argument (XDR *xdrs, cuda_stream_wait_event_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_event_elapsed_time_1_argument (XDR *xdrs, cuda_event_elapsed_time_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_event_record_1_argument (XDR *xdrs, cuda_event_record_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_event_record_with_flags_1_argument (XDR *xdrs, cuda_event_record_with_flags_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_func_set_attributes_1_argument (XDR *xdrs, cuda_func_set_attributes_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_func_set_cache_config_1_argument (XDR *xdrs, cuda_func_set_cache_config_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_func_set_shared_mem_config_1_argument (XDR *xdrs, cuda_func_set_shared_mem_config_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_launch_cooperative_kernel_1_argument (XDR *xdrs, cuda_launch_cooperative_kernel_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_rpc_dim3 (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_rpc_dim3 (xdrs, &objp->arg3))
		 return FALSE;
	 if (!xdr_mem_data (xdrs, &objp->arg4))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg5))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg6))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_launch_kernel_1_argument (XDR *xdrs, cuda_launch_kernel_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_rpc_dim3 (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_rpc_dim3 (xdrs, &objp->arg3))
		 return FALSE;
	 if (!xdr_mem_data (xdrs, &objp->arg4))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg5))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg6))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_occupancy_available_dsmpb_1_argument (XDR *xdrs, cuda_occupancy_available_dsmpb_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_occupancy_max_active_bpm_1_argument (XDR *xdrs, cuda_occupancy_max_active_bpm_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_occupancy_max_active_bpm_with_flags_1_argument (XDR *xdrs, cuda_occupancy_max_active_bpm_with_flags_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg3))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg4))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_host_alloc_1_argument (XDR *xdrs, cuda_host_alloc_1_argument *objp)
{
	 if (!xdr_size_t (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_host_alloc_regshm_1_argument (XDR *xdrs, cuda_host_alloc_regshm_1_argument *objp)
{
	 if (!xdr_size_t (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_host_get_device_pointer_1_argument (XDR *xdrs, cuda_host_get_device_pointer_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_malloc_3d_1_argument (XDR *xdrs, cuda_malloc_3d_1_argument *objp)
{
	 if (!xdr_size_t (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_malloc_3d_array_1_argument (XDR *xdrs, cuda_malloc_3d_array_1_argument *objp)
{
	 if (!xdr_cuda_channel_format_desc (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg3))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg4))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg5))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_malloc_array_1_argument (XDR *xdrs, cuda_malloc_array_1_argument *objp)
{
	 if (!xdr_cuda_channel_format_desc (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg3))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg4))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_malloc_pitch_1_argument (XDR *xdrs, cuda_malloc_pitch_1_argument *objp)
{
	 if (!xdr_size_t (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_mem_advise_1_argument (XDR *xdrs, cuda_mem_advise_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg3))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg4))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_mem_prefetch_async_1_argument (XDR *xdrs, cuda_mem_prefetch_async_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg3))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg4))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_memcpy_htod_1_argument (XDR *xdrs, cuda_memcpy_htod_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_mem_data (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_memcpy_dtoh_1_argument (XDR *xdrs, cuda_memcpy_dtoh_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_memcpy_shm_1_argument (XDR *xdrs, cuda_memcpy_shm_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg3))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg4))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_memcpy_dtod_1_argument (XDR *xdrs, cuda_memcpy_dtod_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_memcpy_to_symbol_1_argument (XDR *xdrs, cuda_memcpy_to_symbol_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_mem_data (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg3))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg4))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_memcpy_to_symbol_shm_1_argument (XDR *xdrs, cuda_memcpy_to_symbol_shm_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg3))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg4))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg5))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_memcpy_ib_1_argument (XDR *xdrs, cuda_memcpy_ib_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg3))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg4))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_memcpy_mt_htod_1_argument (XDR *xdrs, cuda_memcpy_mt_htod_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_memcpy_mt_dtoh_1_argument (XDR *xdrs, cuda_memcpy_mt_dtoh_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_memset_1_argument (XDR *xdrs, cuda_memset_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_memset_2d_1_argument (XDR *xdrs, cuda_memset_2d_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg3))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg4))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg5))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_memset_2d_async_1_argument (XDR *xdrs, cuda_memset_2d_async_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg3))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg4))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg5))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg6))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_memset_3d_1_argument (XDR *xdrs, cuda_memset_3d_1_argument *objp)
{
	 if (!xdr_size_t (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg3))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg4))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg5))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg6))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg7))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg8))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_memset_3d_async_1_argument (XDR *xdrs, cuda_memset_3d_async_1_argument *objp)
{
	 if (!xdr_size_t (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg3))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg4))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg5))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg6))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg7))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg8))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg9))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_memset_async_1_argument (XDR *xdrs, cuda_memset_async_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->arg3))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg4))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_device_can_access_peer_1_argument (XDR *xdrs, cuda_device_can_access_peer_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cuda_device_enable_peer_access_1_argument (XDR *xdrs, cuda_device_enable_peer_access_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cudevicegetattribute_1_argument (XDR *xdrs, rpc_cudevicegetattribute_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cumodulegetfunction_1_argument (XDR *xdrs, rpc_cumodulegetfunction_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->arg2, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cumemcpyhtod_1_argument (XDR *xdrs, rpc_cumemcpyhtod_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_mem_data (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_culaunchkernel_1_argument (XDR *xdrs, rpc_culaunchkernel_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->arg3))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->arg4))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->arg5))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->arg6))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->arg7))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->arg8))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg9))
		 return FALSE;
	 if (!xdr_mem_data (xdrs, &objp->arg10))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cudevicegetp2pattribute_1_argument (XDR *xdrs, rpc_cudevicegetp2pattribute_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cusolverdnsetstream_1_argument (XDR *xdrs, rpc_cusolverdnsetstream_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cusolverdndgetrf_buffersize_1_argument (XDR *xdrs, rpc_cusolverdndgetrf_buffersize_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg3))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg4))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg5))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cusolverdndgetrf_1_argument (XDR *xdrs, rpc_cusolverdndgetrf_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg3))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg4))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg5))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg6))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg7))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg8))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cusolverdndgetrs_1_argument (XDR *xdrs, rpc_cusolverdndgetrs_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg3))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg4))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg5))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg6))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg7))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg8))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg9))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg10))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cublasdgemm_1_argument (XDR *xdrs, rpc_cublasdgemm_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg3))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg4))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg5))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg6))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->arg7))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg8))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg9))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg10))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg11))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->arg12))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg13))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg14))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cublassgemm_1_argument (XDR *xdrs, rpc_cublassgemm_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg3))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg4))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg5))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg6))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->arg7))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg8))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg9))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg10))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg11))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->arg12))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg13))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg14))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cublassgemv_1_argument (XDR *xdrs, rpc_cublassgemv_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg3))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg4))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->arg5))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg6))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg7))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg8))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg9))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->arg10))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg11))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg12))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cublasdgemv_1_argument (XDR *xdrs, rpc_cublasdgemv_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg3))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg4))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->arg5))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg6))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg7))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg8))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg9))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->arg10))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg11))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg12))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cublassgemmex_1_argument (XDR *xdrs, rpc_cublassgemmex_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg3))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg4))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg5))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg6))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->arg7))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg8))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg9))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg10))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg11))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg12))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg13))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->arg14))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->arg15))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg16))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg17))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cublassetstream_1_argument (XDR *xdrs, rpc_cublassetstream_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->handle))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->streamId))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cublassetworkspace_1_argument (XDR *xdrs, rpc_cublassetworkspace_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->handle))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->workspace))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->workspaceSizeInBytes))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cublassetmathmode_1_argument (XDR *xdrs, rpc_cublassetmathmode_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->handle))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cudnnqueryruntimeerror_1_argument (XDR *xdrs, rpc_cudnnqueryruntimeerror_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->handle))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cudnnsetstream_1_argument (XDR *xdrs, rpc_cudnnsetstream_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->handle))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->streamId))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cudnnsettensor4ddescriptor_1_argument (XDR *xdrs, rpc_cudnnsettensor4ddescriptor_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->tensorDesc))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->format))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->dataType))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->n))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->c))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->h))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->w))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cudnnsettensor4ddescriptorex_1_argument (XDR *xdrs, rpc_cudnnsettensor4ddescriptorex_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->tensorDesc))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->dataType))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->n))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->c))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->h))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->w))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nStride))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cStride))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->hStride))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->wStride))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cudnnsettensornddescriptor_1_argument (XDR *xdrs, rpc_cudnnsettensornddescriptor_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->tensorDesc))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->dataType))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nbDims))
		 return FALSE;
	 if (!xdr_mem_data (xdrs, &objp->dimA))
		 return FALSE;
	 if (!xdr_mem_data (xdrs, &objp->strideA))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cudnnsettensornddescriptorex_1_argument (XDR *xdrs, rpc_cudnnsettensornddescriptorex_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->tensorDesc))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->format))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->dataType))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nbDims))
		 return FALSE;
	 if (!xdr_mem_data (xdrs, &objp->dimA))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cudnngettensornddescriptor_1_argument (XDR *xdrs, rpc_cudnngettensornddescriptor_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->tensorDesc))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nbDimsRequested))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cudnntransformtensor_1_argument (XDR *xdrs, rpc_cudnntransformtensor_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->handle))
		 return FALSE;
	 if (!xdr_cudnn_scaling_t (xdrs, &objp->alpha))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->xDesc))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_cudnn_scaling_t (xdrs, &objp->beta))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->yDesc))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->y))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cudnnaddtensor_1_argument (XDR *xdrs, rpc_cudnnaddtensor_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->handle))
		 return FALSE;
	 if (!xdr_cudnn_scaling_t (xdrs, &objp->alpha))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->aDesc))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->A))
		 return FALSE;
	 if (!xdr_cudnn_scaling_t (xdrs, &objp->beta))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->cDesc))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->C))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cudnnsetfilter4ddescriptor_1_argument (XDR *xdrs, rpc_cudnnsetfilter4ddescriptor_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->filterDesc))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->dataType))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->format))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->k))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->c))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->h))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->w))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cudnnsetfilternddescriptor_1_argument (XDR *xdrs, rpc_cudnnsetfilternddescriptor_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->filterDesc))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->dataType))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->format))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nbDims))
		 return FALSE;
	 if (!xdr_mem_data (xdrs, &objp->filterDimA))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cudnngetfilternddescriptor_1_argument (XDR *xdrs, rpc_cudnngetfilternddescriptor_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->filterDesc))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nbDimsRequested))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cudnntransformfilter_1_argument (XDR *xdrs, rpc_cudnntransformfilter_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->handle))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->transDesc))
		 return FALSE;
	 if (!xdr_cudnn_scaling_t (xdrs, &objp->alpha))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->srcDesc))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->srcData))
		 return FALSE;
	 if (!xdr_cudnn_scaling_t (xdrs, &objp->beta))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->destDesc))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->destData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cudnnsoftmaxforward_1_argument (XDR *xdrs, rpc_cudnnsoftmaxforward_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->handle))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->algo))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mode))
		 return FALSE;
	 if (!xdr_cudnn_scaling_t (xdrs, &objp->alpha))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->xDesc))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_cudnn_scaling_t (xdrs, &objp->beta))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->yDesc))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->y))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cudnnsetpooling2ddescriptor_1_argument (XDR *xdrs, rpc_cudnnsetpooling2ddescriptor_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->poolingDesc))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mode))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->maxpoolingNanOpt))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->windowHeight))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->windowWidth))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->verticalPadding))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->horizontalPadding))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->verticalStride))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->horizontalStride))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cudnnsetpoolingnddescriptor_1_argument (XDR *xdrs, rpc_cudnnsetpoolingnddescriptor_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->poolingDesc))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mode))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->maxpoolingNanOpt))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nbDims))
		 return FALSE;
	 if (!xdr_mem_data (xdrs, &objp->windowDimA))
		 return FALSE;
	 if (!xdr_mem_data (xdrs, &objp->paddingA))
		 return FALSE;
	 if (!xdr_mem_data (xdrs, &objp->strideA))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cudnngetpoolingnddescriptor_1_argument (XDR *xdrs, rpc_cudnngetpoolingnddescriptor_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->poolingDesc))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nbDimsRequested))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cudnngetpoolingndforwardoutputdim_1_argument (XDR *xdrs, rpc_cudnngetpoolingndforwardoutputdim_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->poolingDesc))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->inputTensorDesc))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nbDims))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cudnngetpooling2dforwardoutputdim_1_argument (XDR *xdrs, rpc_cudnngetpooling2dforwardoutputdim_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->poolingDesc))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->inputTensorDesc))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cudnnpoolingforward_1_argument (XDR *xdrs, rpc_cudnnpoolingforward_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->handle))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->poolingDesc))
		 return FALSE;
	 if (!xdr_cudnn_scaling_t (xdrs, &objp->alpha))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->xDesc))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_cudnn_scaling_t (xdrs, &objp->beta))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->yDesc))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->y))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cudnnsetactivationdescriptor_1_argument (XDR *xdrs, rpc_cudnnsetactivationdescriptor_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->activationDesc))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mode))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->reluNanOpt))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->coef))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cudnnsetactivationdescriptorswishbeta_1_argument (XDR *xdrs, rpc_cudnnsetactivationdescriptorswishbeta_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->activationDesc))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->swish_beta))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cudnnactivationforward_1_argument (XDR *xdrs, rpc_cudnnactivationforward_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->handle))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->activationDesc))
		 return FALSE;
	 if (!xdr_cudnn_scaling_t (xdrs, &objp->alpha))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->xDesc))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_cudnn_scaling_t (xdrs, &objp->beta))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->yDesc))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->y))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cudnnsetlrndescriptor_1_argument (XDR *xdrs, rpc_cudnnsetlrndescriptor_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->normDesc))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->lrnN))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->lrnAlpha))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->lrnBeta))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->lrnK))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cudnnlrncrosschannelforward_1_argument (XDR *xdrs, rpc_cudnnlrncrosschannelforward_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->handle))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->normDesc))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->lrnMode))
		 return FALSE;
	 if (!xdr_cudnn_scaling_t (xdrs, &objp->alpha))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->xDesc))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_cudnn_scaling_t (xdrs, &objp->beta))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->yDesc))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->y))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cudnngetconvolutionndforwardoutputdim_1_argument (XDR *xdrs, rpc_cudnngetconvolutionndforwardoutputdim_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->convDesc))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->inputTensorDesc))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->filterDesc))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nbDims))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cudnnsetconvolutionnddescriptor_1_argument (XDR *xdrs, rpc_cudnnsetconvolutionnddescriptor_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->convDesc))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arrayLength))
		 return FALSE;
	 if (!xdr_mem_data (xdrs, &objp->padA))
		 return FALSE;
	 if (!xdr_mem_data (xdrs, &objp->filterStrideA))
		 return FALSE;
	 if (!xdr_mem_data (xdrs, &objp->dilationA))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mode))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->computeType))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cudnngetconvolutionforwardalgorithm_v7_1_argument (XDR *xdrs, rpc_cudnngetconvolutionforwardalgorithm_v7_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->handle))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->srcDesc))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->filterDesc))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->convDesc))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->destDesc))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->requestedAlgoCount))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cudnnfindconvolutionforwardalgorithm_1_argument (XDR *xdrs, rpc_cudnnfindconvolutionforwardalgorithm_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->handle))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->xDesc))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->wDesc))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->convDesc))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->yDesc))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->requestedAlgoCount))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cudnngetconvolutionforwardworkspacesize_1_argument (XDR *xdrs, rpc_cudnngetconvolutionforwardworkspacesize_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->handle))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->xDesc))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->wDesc))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->convDesc))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->yDesc))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->algo))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cudnnconvolutionforward_1_argument (XDR *xdrs, rpc_cudnnconvolutionforward_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->handle))
		 return FALSE;
	 if (!xdr_cudnn_scaling_t (xdrs, &objp->alpha))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->xDesc))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->wDesc))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->w))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->convDesc))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->algo))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->workSpace))
		 return FALSE;
	 if (!xdr_size_t (xdrs, &objp->workSpaceSizeInBytes))
		 return FALSE;
	 if (!xdr_cudnn_scaling_t (xdrs, &objp->beta))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->yDesc))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->y))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cudnnbackendsetattribute_1_argument (XDR *xdrs, rpc_cudnnbackendsetattribute_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->descriptor))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->attributeName))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->attributeType))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->elementCount))
		 return FALSE;
	 if (!xdr_mem_data (xdrs, &objp->arrayOfElements))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cudnnbackendgetattribute_1_argument (XDR *xdrs, rpc_cudnnbackendgetattribute_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->descriptor))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->attributeName))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->attributeType))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->requestedElementCount))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cudnnbackendexecute_1_argument (XDR *xdrs, rpc_cudnnbackendexecute_1_argument *objp)
{
	 if (!xdr_ptr (xdrs, &objp->handle))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->executionPlan))
		 return FALSE;
	 if (!xdr_ptr (xdrs, &objp->variantPack))
		 return FALSE;
	return TRUE;
}
